.TH "GIT-RANDOM" 1 "September 23 2024" "git-random 2.0.1" "User Commands"
.SH NAME
git-random \- build random-content Git trees quickly
.SH SYNOPSIS

\fBgit activity\fR \fBpost-checkout-record\fR \fI\<Git post-checkout hook parameters\>\fR

\fBgit activity\fR \fBrecord\fR \fI\<message\>\fR

\fBgit activity\fR \fBshow\fR [\fI\<date\>\fR]

\fBgit random\fR (\fBhelp\fR | \fB--help\fR)

\fBgit random\fR (\fB--version\fR | \fB-v\fR)

.SH DESCRIPTION
\fBgit-random\fR is a tool for helping with Git practice and experimentation.
Build commit history quickly by creating and committing randomly-named files
with random content.

.SH COMMANDS
The following commands are available:

.IP \(bu
\fBgit activity\fR \fBrecord\fR \fI\<message\>\fR

Record an activity message.

.IP \(bu
\fBgit activity\fR \fBpost-checkout-record\fR \fI\<Git post-checkout hook parameters\>\fR

Record activity from a post-checkout hook.

If the checked out branch does not appear in the reflog and does not have
a remote tracking branch, it is recorded as \fIcreate\fR.

N.B: this has a false negative when creating a branch the name of which
you have used before recently enough for it to still be in the reflog.

.IP \(bu
\fBgit activity\fR \fBshow\fR [\fI\<date\>\fR]

Show the recorded activity for the given date (default: current date).

.IP \(bu
\fBgit random\fR (\fBhelp\fR | \fB--help\fR)

Show this document.

.IP \(bu
\fBgit random\fR (\fB--version\fR | \fB-v\fR)

Show the current version.

.SH AUTHORS

Henry Bley\-Vroman <olets@olets.dev>
