name: Bump Homebrew Formula on Release Publication

on:
  release:
    types: [released]
  workflow_dispatch:
jobs:
  homebrew:
    name: Bump Homebrew formulae
    runs-on: ubuntu-latest
    steps:
      - name: Bump primary formula
        if: "contains(github.ref, 'v1')"
        uses: mislav/bump-homebrew-formula-action@b3327118b2153c82da63fd9cbf58942146ee99f0 # v3.1
        with:
          formula-name: git-activity
          formula-path: git-activity.rb
          homebrew-tap: olets/homebrew-tap
          commit-message: |
            feat({{formulaName}}): publish {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
            via the https://github.com/olets/git-activity "bump-homebrew-formula-on-release-publication" workflow
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
      - name: Bump v1.x formula
        if: "contains(github.ref, 'v1')"
        uses: mislav/bump-homebrew-formula-action@b3327118b2153c82da63fd9cbf58942146ee99f0 # v3.1
        with:
          formula-name: git-activity@1
          formula-path: git-activity@1.rb
          homebrew-tap: olets/homebrew-tap
          commit-message: |
            feat({{formulaName}}): publish {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
            via the https://github.com/olets/git-activity "bump-homebrew-formula-on-release-publication" workflow
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
